export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_MESSAGE = "CHANGE_MESSAGE";
export const DELETE_PRODUCT_CART = "DELETE_PRODUCT_CART";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const COMPLETE_PURCHASE = "COMPLETE_PURCHASE";
